serviceAccounts:
  server:
    name: amp-iamproxy-ingest-service-account
    annotations: 
      eks.amazonaws.com/role-arn: arn:aws:iam::{ACCOUNTID}:role/{EKSCLUSTER_NAME}-prometheus-ingest
server:
  remoteWrite:
    - url: https://aps-workspaces.{AWS_REGION}.amazonaws.com/workspaces/{WORKSPACE_ID}/api/v1/remote_write
      sigv4:
        region: {AWS_REGION}
      queue_config:
        max_samples_per_send: 3000
        batch_send_deadline: 10s
        min_shards: 4
        max_shards: 200
        capacity: 10000
alertmanager:
  enabled: false